<a href="https://colab.research.google.com/github/Kolosocc/Convert/blob/main/First.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.array([5.2, 3.1, 8.9])
b = np.array([1.7, 3.5, 4.9])
print(np.sum([a, b]))

27.300000000000004


In [8]:
import numpy as np

v = np.array([0.2, 8.3, 7.8, 4.7, 6.4])

v = np.insert(v, 0, 1.1)
v = np.insert(v, 2, 3.3)
v = np.insert(v, 5, 5.5)

print(v)



[1.1 0.2 3.3 8.3 7.8 5.5 4.7 6.4]


In [13]:
import numpy as np

w = np.array([1.8, 6.4, 9.3, 0.5, 2.1, 3.7, 2.9])

w[2:7] = 0

w1 = w[1:5]
print(w1)

w2 = np.concatenate((w[:1], w[2:]))
print(w2)


[6.4 0.  0.  0. ]
[1.8 0.  0.  0.  0.  0. ]


In [18]:
import numpy as np

z = np.array([2.2, 4.1, 8.9, 3.2, 2.1, 5.8, 2.1, 2.1, 9.7])

maxNum = np.max(z)
minNum = np.min(z)

maxI = np.where(z == maxNum)[0][0]

print(maxNum, minNum, maxI)

9.7 2.1 [8]


In [22]:
import numpy as np

r = np.array([-0.2, 6.3, -9.4, 3.8, 7.4, 0.1])

a = np.sort(r)

b = np.sort(r)[::-1]

print(a)
print(b)


[-9.4 -0.2  0.1  3.8  6.3  7.4]
[ 7.4  6.3  3.8  0.1 -0.2 -9.4]


In [35]:
import numpy as np

v1 = np.array([2, 8, -4, 3])
v2 = np.array([-5, 7, -3, 1])

print(np.dot(v1,v2))
print(v1 ** 2)
print('[' + ' '.join(map(str, v1 / v2)) + ']')
print('[' + ' '.join(map(str, v2 / v1)) + ']')

61
[ 4 64 16  9]
[-0.4 1.1428571428571428 1.3333333333333333 3.0]
[-2.5 0.875 0.75 0.3333333333333333]


In [43]:
import numpy as np

ascii = np.arange(97, 123)
alphabetChars = np.char.mod('%c', ascii)
alphabet = ''.join(alphabetChars)
print(alphabet)

print( ''.join(alphabet[1::2]))
print( ''.join(alphabet[6::7]))

input_file_path = "input.txt"
output_file_path = "output.txt"

with open(input_file_path, 'r') as input_file:
    text = input_file.read()
    text_array = np.array(list(text))

    with open(output_file_path, 'w') as output_file:
        output_file.write(''.join(text_array[1::2]) + '\n' + ''.join(text_array[6::7]))



abcdefghijklmnopqrstuvwxyz
bdfhjlnprtvxz
gnu
output.txt
